version: '3.8'

services:
  vtiger:
    build: .
    ports:
      - 8080:80
    volumes:
      - vtiger:/var/lib/vtiger
      - www:/var/www
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: pw
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
  vtiger:
  www: